In [8]:
import os
import json
import pickle
import numpy as np

In [9]:
from nltk.corpus import wordnet as wn

In [10]:
with open('VG-SGG-dicts.json', 'r') as fin:
    scene_graph_meta = json.load(fin)

In [11]:
labels = list(scene_graph_meta['label_to_idx'].keys())

In [48]:
with open('VG-SGG-dicts_combined_176_20211107.json', 'r') as fin:
    scene_graph_meta_177 = json.load(fin)
    
# labels_new = list(scene_graph_meta_177['index'].keys())

In [21]:
scene_graph_meta_177['idx_to_label']

{'1': 'airplane',
 '2': 'animal',
 '3': 'arm',
 '4': 'bag',
 '5': 'banana',
 '6': 'basket',
 '7': 'beach',
 '8': 'bear',
 '9': 'bed',
 '10': 'bench',
 '11': 'bike',
 '12': 'bird',
 '13': 'board',
 '14': 'boat',
 '15': 'book',
 '16': 'boot',
 '17': 'bottle',
 '18': 'bowl',
 '19': 'box',
 '20': 'boy',
 '21': 'branch',
 '22': 'building',
 '23': 'bus',
 '24': 'cabinet',
 '25': 'cap',
 '26': 'car',
 '27': 'cat',
 '28': 'chair',
 '29': 'child',
 '30': 'clock',
 '31': 'coat',
 '32': 'counter',
 '33': 'cow',
 '34': 'cup',
 '35': 'curtain',
 '36': 'desk',
 '37': 'dog',
 '38': 'door',
 '39': 'drawer',
 '40': 'ear',
 '41': 'elephant',
 '42': 'engine',
 '43': 'eye',
 '44': 'face',
 '45': 'fence',
 '46': 'finger',
 '47': 'flag',
 '48': 'flower',
 '49': 'food',
 '50': 'fork',
 '51': 'fruit',
 '52': 'giraffe',
 '53': 'girl',
 '54': 'glass',
 '55': 'glove',
 '56': 'guy',
 '57': 'hair',
 '58': 'hand',
 '59': 'handle',
 '60': 'hat',
 '61': 'head',
 '62': 'helmet',
 '63': 'hill',
 '64': 'horse',
 '65': '

In [336]:
for label in labels:
    print('************', label)
    for syn in wn.synsets(label):
        print(syn, syn.definition())

************ kite
Synset('kite.n.01') a bank check that has been fraudulently altered to increase its face value
Synset('kite.n.02') a bank check drawn on insufficient funds at another bank in order to take advantage of the float
Synset('kite.n.03') plaything consisting of a light frame covered with tissue paper; flown in wind at end of a string
Synset('kite.n.04') any of several small graceful hawks of the family Accipitridae having long pointed wings and feeding on insects and small animals
Synset('kite.v.01') increase the amount (of a check) fraudulently
Synset('kite.v.02') get credit or money by using a bad check
Synset('kite.v.03') soar or fly like a kite
Synset('kite.v.04') fly a kite
************ pant
Synset('pant.n.01') the noise made by a short puff of steam (as from an engine)
Synset('trouser.n.01') (usually in the plural) a garment extending from the waist to the knee or ankle, covering each leg separately
Synset('gasp.n.01') a short labored intake of breath with the mouth o

In [3]:
import pandas as pd
df_excluded_keep_original_51 = pd.read_csv('df_excluded_keep_original_51.csv')

In [13]:
synsets_wiki = list(df_excluded_keep_original_51['synset'])
labels_wiki = list(df_excluded_keep_original_51['entity_tail_wikidata'])


In [6]:
# 1. Map Old Synset with old labels2order. Wait never mind it's not alphabetical

In [315]:
synsets = [
    'kite.n.03',
    'trouser.n.01',
    'bowl.n.01',
    'laptop.n.01',
    'paper.n.01',
    'motorcycle.n.01',
    'railing.n.01',
    'chair.n.01',
    'windshield.n.01',
    'tire.n.01',
    'cup.n.01',
    'bench.n.01',
    'tail.n.01',
    'bicycle.n.01',
    'board.n.03',
    'orange.n.01',
    'hat.n.01',
    'finger.n.01',
    'plate.n.04',
    'woman.n.01',
    'handle.n.01',
    'branch.n.02',
    'food.n.01',
    'bear.n.01',
    'vase.n.01',
    'vegetable.n.01',
    'giraffe.n.01',
    'desk.n.01',
    'lady.n.01',
    'towel.n.01',
    'glove.n.02',
    'bag.n.01',
    'nose.n.01',
    'rock.n.01',
    'guy.n.01',
    'shoe.n.01',
    'gym_shoe.n.01',
    'fence.n.01',
    'people.n.01',
    'house.n.01',
    'seat.n.01',
    'hair.n.01',
    'street.n.02',
    'roof.n.01',
    'racket.n.04',
    'logo.n.01',
    'female_child.n.01',
    'arm.n.01',
    'flower.n.01',
    'leaf.n.01',
    'clock.n.01',
    'hill.n.01',
    'bird.n.01',
    'umbrella.n.01',
    'leg.n.01',
    'screen.n.03',
    'man.n.01',
    'sink.n.01',
    'trunk.n.01',
    'post.n.04',
    'sidewalk.n.01',
    'box.n.01',
    'male_child.n.01',
    'cow.n.01',
    'skateboard.n.01',
    'airplane.n.01',
    'stand.n.04',
    'pillow.n.01',
    'ski.n.01',
    'wire.n.02',
    'toilet.n.02',
    'pot.n.01',
    'sign.n.02',
    'numeral.n.01',
    'pole.n.01',
    'table.n.02',
    'boat.n.01',
    'sheep.n.01',
    'horse.n.01',
    'eye.n.01',
    'sock.n.01',
    'window.n.01',
    'vehicle.n.01',
    'curtain.n.01',
    'child.n.01',
    'banana.n.01',
    'engine.n.01',
    'head.n.01',
    'door.n.01',
    'bus.n.01',
    'cabinet.n.01',
    'glass.n.02',
    'flag.n.01',
    'train.n.01',
    'child.n.01',
    'ear.n.01',
    'surfboard.n.01',
    'room.n.01',
    'player.n.01',
    'car.n.01',
    'cap.n.01',
    'tree.n.01',
    'bed.n.01',
    'cat.n.01',
    'coat.n.01',
    'skier.n.01',
    'zebra.n.01',
    'fork.n.01',
    'drawer.n.01',
    'airplane.n.01',
    'helmet.n.01',
    'shirt.n.01',
    'paw.n.01',
    'boot.n.01',
    'snow.n.02',
    'lamp.n.01',
    'book.n.02',
    'animal.n.01',
    'elephant.n.01',
    'tile.n.01',
    'necktie.n.01',
    'beach.n.01',
    'pizza.n.01',
    'wheel.n.01',
    'plant.n.02',
    'tower.n.01',
    'mountain.n.01',
    'path.n.04',
    'hand.n.01',
    'fruit.n.01',
    'mouth.n.01',
    'letter.n.02',
    'shelf.n.01',
    'wave.n.01',
    'man.n.01',
    'building.n.01',
    'short_pants.n.01',
    'neck.n.01',
    'telephone.n.01',
    'light.n.02',
    'counter.n.01',
    'dog.n.01',
    'face.n.01',
    'jacket.n.01',
    'person.n.01',
    'truck.n.01',
    'bottle.n.01',
    'basket.n.01',
    'jean.n.01',
    'wing.n.02',
]

In [316]:
len(synsets)

150

In [317]:
label2synset = {l: s for l, s in zip(labels, synsets)}

In [54]:
labels_new = list(scene_graph_meta_177['label_to_idx'].keys())

176

In [83]:
# word_sim = np.zeros((3, 151, 151))
from utils import load_obj
label2synset_combined = load_obj('label2synset_combined')
# idx2label_177 = {str(idx+1): label for idx, label in enumerate(sorted(scene_graph_meta_177['label_to_idx']))}
idx2label_177 = {str(v): k for k, v in sorted(scene_graph_meta_177['label_to_idx'].items(), key=lambda item: item[1])}
labels_new = sorted(list(scene_graph_meta_177['label_to_idx'].keys()))
num_nouns = len(labels_new)
word_sim = np.zeros((3, num_nouns+1, num_nouns+1))
# the iteration starts from 1 because the dict keys start with 1
for i in idx2label_177:
    for j in idx2label_177:
        if i == j:
            continue
#         if idx2label_177[i] == 'person' and idx2label_177[j] == 'man':
#             import pdb; pdb.set_trace()
        a = wn.synset(label2synset_combined[idx2label_177[i]])
        b = wn.synset(label2synset_combined[idx2label_177[j]])
        s1 = a.path_similarity(b)
        s2 = a.lch_similarity(b) / 3.6375861597263857
        s3 = a.wup_similarity(b)
        word_sim[:, int(i), int(j)] = [s1, s2, s3]
        

In [84]:
# {str(v): k for k, v in sorted(scene_graph_meta_177['label_to_idx'].items(), key=lambda item: item[1])}

In [63]:
len(scene_graph_meta_177['label_to_idx'])

176

In [64]:
word_sim.shape

(3, 177, 177)

In [58]:
num_nouns

176

In [72]:
label_to_index_151 = scene_graph_meta['label_to_idx']
idx_to_label_151 = scene_graph_meta['idx_to_label']


In [85]:
# actual: i = 91, j = 78
# expected: 
word_sim[:, scene_graph_meta_177['label_to_idx']['person'], scene_graph_meta_177['label_to_idx']['man']] # array([0.33333333, 0.69798316, 0.75      ])

array([0.33333333, 0.69798316, 0.75      ])

In [86]:
word_sim_thresh = np.any(word_sim >= [[[0.2]], [[0.5]], [[0.7]]], axis=0).astype(np.float32)

In [87]:
word_sim_thresh[scene_graph_meta_177['label_to_idx']['person'], scene_graph_meta_177['label_to_idx']['man']]

1.0

In [88]:
word_sim_thresh[scene_graph_meta_177['label_to_idx']['person'], scene_graph_meta_177['label_to_idx']['lady']]

1.0

In [89]:
word_sim_thresh[scene_graph_meta_177['label_to_idx']['girl'], scene_graph_meta_177['label_to_idx']['lady']]

1.0

In [90]:
word_sim_thresh[scene_graph_meta_177['label_to_idx']['woman'], scene_graph_meta_177['label_to_idx']['lady']]

1.0

In [91]:
word_sim_thresh[scene_graph_meta_177['label_to_idx']['woman'], scene_graph_meta_177['label_to_idx']['pizza']]

0.0

In [332]:
preds = list(scene_graph_meta['predicate_to_idx'].keys())

In [335]:
for label in preds:
    print('************', label)
    for syn in wn.synsets(label):
        print(syn, syn.definition())
    if ' ' in label:
        print('************')
        for syn in wn.synsets(label.split(' ')[0]):
            print(syn, syn.definition())


************ and
************ says
Synset('say.n.01') the chance to speak
Synset('state.v.01') express in words
Synset('allege.v.01') report or maintain
Synset('suppose.v.01') express a supposition
Synset('read.v.02') have or contain a certain wording or form
Synset('order.v.01') give instructions to or direct somebody to do something with authority
Synset('pronounce.v.01') speak, pronounce, or utter in a certain way
Synset('say.v.07') communicate or express nonverbally
Synset('say.v.08') utter aloud
Synset('say.v.09') state as one's opinion or judgement; declare
Synset('say.v.10') recite or repeat a fixed text
Synset('say.v.11') indicate
************ belonging to
************
Synset('belonging.n.01') happiness felt in a secure relationship
Synset('belong.v.01') be owned by; be in the possession of
Synset('belong.v.02') be suitable or acceptable
Synset('belong.v.03') be in the right place or situation
Synset('belong.v.04') be rightly classified in a class or category
Synset('belong.v.0

In [392]:
pred_syns = [
    '',
    'say.v.07',
    'belong.v.01',
    'over.r.04',
    'park.v.01',
    'grow.v.07',
    'stand.v.01',
    'make.v.34',
    'attach.v.02',
    '',
    'in.r.01',
    'hang.v.01',
    'wear.v.01',
    'ahead.r.01',
    '',
    'belong.v.01',
    'watch.v.01',
    'lie.v.02',
    '',
    'behind.r.01',
    'fly.v.01',
    'look.v.01',
    '',
    'hold.v.02',
    'between.r.02',
    'lie.v.02',
    'ride.v.02',
    'have.v.01',
    'across.r.01',
    'wear.v.01',
    'walk.v.01',
    'eat.v.01',
    'above.r.02',
    'constitute.v.01',
    'walk.v.01',
    'sit.v.01',
    'nether.s.03',
    'covered.a.01',
    'transport.v.02',
    'use.v.01',
    '',
    '',
    '',
    'cover.v.02',
    'belong.v.01',
    '',
    'play.v.01',
    'near.r.01',
    'paint.v.01',
    'mount.v.01'
]

In [393]:
len(pred_syns)

50

In [394]:
pred2synset = {l: s for l, s in zip(preds, pred_syns)}

In [395]:
pred2synset

{'and': '',
 'says': 'say.v.07',
 'belonging to': 'belong.v.01',
 'over': 'over.r.04',
 'parked on': 'park.v.01',
 'growing on': 'grow.v.07',
 'standing on': 'stand.v.01',
 'made of': 'make.v.34',
 'attached to': 'attach.v.02',
 'at': '',
 'in': 'in.r.01',
 'hanging from': 'hang.v.01',
 'wears': 'wear.v.01',
 'in front of': 'ahead.r.01',
 'from': '',
 'for': 'belong.v.01',
 'watching': 'watch.v.01',
 'lying on': 'lie.v.02',
 'to': '',
 'behind': 'behind.r.01',
 'flying in': 'fly.v.01',
 'looking at': 'look.v.01',
 'on back of': '',
 'holding': 'hold.v.02',
 'between': 'between.r.02',
 'laying on': 'lie.v.02',
 'riding': 'ride.v.02',
 'has': 'have.v.01',
 'across': 'across.r.01',
 'wearing': 'wear.v.01',
 'walking on': 'walk.v.01',
 'eating': 'eat.v.01',
 'above': 'above.r.02',
 'part of': 'constitute.v.01',
 'walking in': 'walk.v.01',
 'sitting on': 'sit.v.01',
 'under': 'nether.s.03',
 'covered in': 'covered.a.01',
 'carrying': 'transport.v.02',
 'using': 'use.v.01',
 'along': '',
 'w

In [413]:
pred_sim = np.zeros((3, 51, 51))
for i in scene_graph_meta['idx_to_predicate']:
    for j in scene_graph_meta['idx_to_predicate']:
        if i == j:
            continue
        a = pred2synset[scene_graph_meta['idx_to_predicate'][i]]
        b = pred2synset[scene_graph_meta['idx_to_predicate'][j]]
        if a == '' or b == '':
            continue
        a = wn.synset(a)
        b = wn.synset(b)
        try:
            s1 = a.path_similarity(b)
        except:
            s1 = None
        try:
            s2 = a.lch_similarity(b)
        except:
            s2 = None
        try:
            s3 = a.wup_similarity(b)
        except:
            s3 = None
        if s1 == None: 
            s1 = 0.0
        if s2 == None: 
            s2 = 0.0
        else:
            s2 /= 3.6375861597263857
        if s3 == None: 
            s3 = 0.0
        pred_sim[:, int(i), int(j)] = [s1, s2, s3]
        

In [397]:
pred_sim_thresh = np.any(pred_sim >= [[[0.2]], [[0.5]], [[0.7]]], axis=0).astype(np.float32)

In [423]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['attached to'], scene_graph_meta['predicate_to_idx']['sitting on']]

array([0.25     , 0.5145726, 0.4      ])

In [420]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['lying on'], scene_graph_meta['predicate_to_idx']['sitting on']]

array([0.33333333, 0.59365858, 0.5       ])

In [421]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['watching'], scene_graph_meta['predicate_to_idx']['looking at']]

array([0.33333333, 0.59365858, 0.5       ])

In [424]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['riding'], scene_graph_meta['predicate_to_idx']['sitting on']]

array([0.2       , 0.45322875, 0.33333333])

In [425]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['riding'], scene_graph_meta['predicate_to_idx']['on back of']]

array([0., 0., 0.])

In [426]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['riding'], scene_graph_meta['predicate_to_idx']['carrying']]

array([0.16666667, 0.40310717, 0.28571429])

In [427]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['standing on'], scene_graph_meta['predicate_to_idx']['parked on']]

array([0.14285714, 0.36072998, 0.25      ])

In [ ]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['standing on'], scene_graph_meta['predicate_to_idx']['parked on']]

In [428]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['attached to'], scene_graph_meta['predicate_to_idx']['mounted on']]

array([0.16666667, 0.40310717, 0.28571429])

In [429]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['eating'], scene_graph_meta['predicate_to_idx']['riding']]

array([0.16666667, 0.40310717, 0.28571429])

In [431]:
pred_sim[:, scene_graph_meta['predicate_to_idx']['holding'], scene_graph_meta['predicate_to_idx']['has']]

array([0.33333333, 0.59365858, 0.5       ])

In [432]:
wn.synset('hold.v.02').path_similarity(wn.synset('have.v.01'))

0.3333333333333333

In [434]:
wn.synset('hold.v.02').lch_similarity(wn.synset('have.v.01')) / 3.6375861597263857

0.5936585841628025

In [399]:
for i in range(51):
    for j in range(51):
        if pred_sim_thresh[i, j] == 1:
            print(scene_graph_meta['idx_to_predicate'][str(i)], scene_graph_meta['idx_to_predicate'][str(j)])

attached to covering
attached to hanging from
attached to has
attached to holding
attached to laying on
attached to looking at
attached to lying on
attached to part of
attached to sitting on
attached to using
attached to watching
attached to wearing
attached to wears
belonging to for
belonging to hanging from
belonging to has
belonging to holding
belonging to laying on
belonging to looking at
belonging to lying on
belonging to of
belonging to part of
belonging to sitting on
belonging to standing on
belonging to using
belonging to watching
belonging to wearing
belonging to wears
carrying hanging from
carrying has
carrying holding
carrying laying on
carrying looking at
carrying lying on
carrying parked on
carrying part of
carrying sitting on
carrying using
carrying watching
carrying wearing
carrying wears
covering attached to
covering hanging from
covering has
covering holding
covering laying on
covering looking at
covering lying on
covering part of
covering sitting on
covering using
cov

In [402]:
2.0 / 3.6375861597263857

0.5498151554849872

In [92]:
# from utils import save_obj
# save_obj(word_sim_thresh, 'wordnet_e2e_graph')

In [403]:
# with open(os.path.join('/home/alireza/workspace/vsp-net-old', 'metadata', 'VG', 'prep', 'stanford', 'wordnet_e2e_graph.pkl'), 'wb') as fout:
#     pickle.dump(word_sim_thresh, fout)

In [407]:
a = wn.synset(b)

In [412]:
with open(os.path.join('/home/alireza/workspace/vsp-net-old', 'metadata', 'VG', 'prep', 'stanford', 'graphs', 'label2synset.pkl'), 'wb') as fout:
    pickle.dump((label2synset, pred2synset), fout)